### ISSUE TITLE
After close the SSH connection, the clash service will automatically close

### ISSUE THREAD

**Issue by LeeSpo** [spencerwooo/clashrup#23]
I use this on RaspPie 3 (OS: RHEL Branch), which severs as a proxy server.
Following the instructions and setting up, all things run smoothly as expected.
However, after closing the SSH connection, the service automatically turns to `loaded` status.
Manually re-login and executiveing the `clashrup start` , it starts working. Closing the SSH connection, it downs again.
I'm wondering how to fix that.
BTW, how to enable clashrup start when the system boots? I've tried `systemctl enable clash` but it returned `clash.service` not found.
Thanks 😵‍💫

**Comment by spencerwooo** [comment]
> However, after closing the SSH connection, the service automatically turns to loaded status.

Yes, because you (as the user who created the systemd service) logged out, which will automatically stop all user-created systemd services. You would need to invoke `clashrup` as a sudo user, with some locations changed (in `clashrup.toml`):

```toml
clash_binary_path = "/usr/local/bin/clash"
clash_config_root = "/etc/clash/"
user_systemd_root = "/etc/systemd/system/"
```

Additionally, all `systemctl` commands are hard-coded as user actions currently (with `--user`), so options like `start`, `status`, `log`, etc., will no longer work under sudo mode. You need to manually call these commands (as in `sudo systemctl status clash`).

**Comment by spencerwooo** [comment]
> BTW, how to enable clashrup start when the system boots?

After creating the systemd service as root, the service should start on boot.

**Comment by spencerwooo** [comment]
Again, `clashrup` is not designed to be used as root currently, so all operations I mentioned above may or may not work :(

**Comment by LeeSpo** [comment]
> invoke
I tried to setup clashrup using sudo -i 
It returned:
`Failed to connect to bus: No such file or directory`

**Comment by LeeSpo** [comment]
> Yes, because you (as the user who created the systemd service) logged out, which will automatically stop all user-created systemd services. You would need to invoke clashrup as a sudo user, with some locations changed (in clashrup.toml):

But that's weird.
I installed it twice because I re-installed the OS for some reason. 
The first time, it worked, no existing after closing SSH. It works perfectly.
The second time, doing the same process, it exited. 😨

Sorry for my poor English.

**Comment by spencerwooo** [comment]
Just published a new version which modifies the systemd file to use `default.target` instead of the original `multi-user.target`. After some investigation, I think the best option would be to:

* Use `clashrup` and create clash services **under non-root user**, and...
* Enable starting clash's user systemd service on login with:

  ```bash
  loginctl enable-linger {username}
  ```
  Ref: [System service running as user is terminated on logout](https://unix.stackexchange.com/questions/521538/system-service-running-as-user-is-terminated-on-logout)

**Comment by LeeSpo** [comment]
![image](https://user-images.githubusercontent.com/75921239/212274528-d856f84e-3fba-44be-8cbd-4da77df1af71.png)
**thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/utils.rs:103:47**
Another bug occured after fixing a bug 🤣

**Comment by spencerwooo** [comment]
lol, you need to change your settings back remember? (Config file `~/.config/clashrup.toml`)

**Comment by spencerwooo** [comment]
> ... which modifies the systemd file to use default.target instead of the original multi-user.target

I found that even without `loginctl enable-linger {username}`, my clash systemd service was not stopped after logging out. I wonder if that is the case on your side? @LeeSpo 

Closing this issue for now as I believe this is fixed. If not, feel free to reopen.

**Comment by LeeSpo** [comment]
`I found that after this modification, even without loginctl enable-linger {username}, my clash systemd service was not stopped after logging out. `
The same on my side and I think it's perfectly solved. Thanks.
